//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloatRemove.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloatRemove.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] adb {
            get {
                object obj = ResourceManager.GetObject("adb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] AdbWinApi {
            get {
                object obj = ResourceManager.GetObject("AdbWinApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] AdbWinUsbApi {
            get {
                object obj = ResourceManager.GetObject("AdbWinUsbApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] dmtracedump {
            get {
                object obj = ResourceManager.GetObject("dmtracedump", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] dummy {
            get {
                object obj = ResourceManager.GetObject("dummy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] etc1tool {
            get {
                object obj = ResourceManager.GetObject("etc1tool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] fastboot {
            get {
                object obj = ResourceManager.GetObject("fastboot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] HAL3_ENABLE_MIUI_PIE {
            get {
                object obj = ResourceManager.GetObject("HAL3_ENABLE_MIUI_PIE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] hprof_conv {
            get {
                object obj = ResourceManager.GetObject("hprof_conv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] libwinpthread_1 {
            get {
                object obj = ResourceManager.GetObject("libwinpthread_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] make_f2fs {
            get {
                object obj = ResourceManager.GetObject("make_f2fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] mke2fs {
            get {
                object obj = ResourceManager.GetObject("mke2fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] mke2fs1 {
            get {
                object obj = ResourceManager.GetObject("mke2fs1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notices for files contained in the tools directory:
        ///============================================================
        ///Notices for file(s):
        ////lib/libfec_rs.a
        ////lib64/libfec_rs.a
        ///------------------------------------------------------------
        ///		  GNU LESSER GENERAL PUBLIC LICENSE
        ///		       Version 2.1, February 1999
        ///
        /// Copyright © 1991, 1999 Free Software Foundation, Inc.
        ///     59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, b [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string NOTICE {
            get {
                return ResourceManager.GetString("NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloaded from
        ///https://miui.blog/
        ///
        ///The #1 Source of MIUI Update
        ///
        ///=================================
        ///- MIUI Tips and Tricks
        ///- MIUI ROM Download
        ///- Custom ROM Download
        ///- TWRP / RWRP Recovery for Xiaomi devices
        ///- Magisk Root Xiaomi devices
        ///- Unbrick, unlock bootloader, etc.
        ///
        ///Visit =&gt; https://miui.blog/.
        /// </summary>
        internal static string README {
            get {
                return ResourceManager.GetString("README", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] source {
            get {
                object obj = ResourceManager.GetObject("source", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] sqlite3 {
            get {
                object obj = ResourceManager.GetObject("sqlite3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
